name       : gnome-music
version    : 3.18.2
release    : 1
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-music/3.18/gnome-music-3.18.2.tar.xz : 81b6ae8b4193774a1dc05e77c59ad8ff5e7debc0aea30ce2ecd13b2ceda10bff
license    : GPL-2.0
summary    : Music is the new GNOME music playing application.
description: |
    Music is the new GNOME music playing application. It aims to combine an elegant and immersive browsing experience with simple and straightforward controls.
builddeps  :
    - pkgconfig(dbus-python)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(grilo-0.2)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libmediaart-2.0)
    - pkgconfig(py3cairo)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python-3.4)
    - pkgconfig(tracker-control-1.0)
    - intltool
    - itstool
    - grilo-plugins
    - gvfs-devel
    - python-requests
rundeps:
    - python-cairo
    - python-dbus
    - python-gobject
    - python-requests
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
