name       : gnome-music
version    : 3.24.2
release    : 7
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/gnome-music/3.24/gnome-music-3.24.2.tar.xz : 1a72b7972cac66c7aba7a4fbcbf8df99b3df7c46f26957b3e16089550d3ef62c
license    : GPL-2.0
component  : multimedia.audio
summary    : Music is the new GNOME music playing application.
description: |
    Music is the new GNOME music playing application. It aims to combine an elegant and immersive browsing experience with simple and straightforward controls.
builddeps  :
    - pkgconfig(exempi-2.0)
    - pkgconfig(flac)
    - pkgconfig(gee-0.8)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(grilo-0.3)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(icu-i18n)
    - pkgconfig(libcue)
    - pkgconfig(libexif)
    - pkgconfig(libgsf-1)
    - pkgconfig(libmediaart-2.0)
    - pkgconfig(libnautilus-extension)
    - pkgconfig(libsecret-1)
    - pkgconfig(poppler-glib)
    - pkgconfig(py3cairo)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python-3.5)
    - pkgconfig(taglib)
    - pkgconfig(totem-plparser)
    - pkgconfig(tracker-control-1.0)
    - pkgconfig(upower-glib)
    - pkgconfig(vorbis)
    - grilo-plugins
    - gvfs-devel
    - itstool
    - python3-dbus
    - python-requests
    - vala
rundeps    :
    - dleyna-connector-dbus
    - dleyna-server
    - grilo-plugins
    - python3-cairo
    - python3-dbus
    - python-gobject
    - python-requests
    - tracker
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
