name       : gnome-music
version    : '42.1'
release    : 39
source     :
    - https://download.gnome.org/sources/gnome-music/42/gnome-music-42.1.tar.xz : c7747fa6a86b56b18ad6ff950ff901e59ee7fac11c68b2a6727af86eaeed8270
homepage   : https://wiki.gnome.org/Apps/Music
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : Music is the new GNOME music playing application
description: |
    Music is the new GNOME music playing application. It aims to combine an elegant and immersive browsing experience with simple and straightforward controls.
builddeps  :
    - pkgconfig(flac)
    - pkgconfig(gee-0.8)
    - pkgconfig(grilo-0.3)
    - pkgconfig(grilo-plugins-0.3)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(goa-1.0)
    - pkgconfig(libadwaita-1)
    - pkgconfig(libcue)
    - pkgconfig(libdazzle-1.0)
    - pkgconfig(libexif)
    - pkgconfig(libgsf-1)
    - pkgconfig(libmediaart-2.0)
    - pkgconfig(libnautilus-extension)
    - pkgconfig(libsecret-1)
    - pkgconfig(poppler-glib)
    - pkgconfig(py3cairo)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python3)
    - pkgconfig(taglib)
    - pkgconfig(totem-plparser)
    - pkgconfig(tracker-sparql-3.0)
    - pkgconfig(upower-glib)
    - pkgconfig(vorbis)
    - desktop-file-utils
    - gvfs-devel
    - itstool
    - python3-dbus
    - python-requests
    - vala
rundeps    :
    - dleyna-connector-dbus
    - dleyna-server
    - grilo-plugins
    - libdazzle
    - python-gobject
    - python-requests
    - python3-dbus
    - tracker
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
