name       : gnome-music
version    : 3.38.1
release    : 29
source     :
    - https://download.gnome.org/sources/gnome-music/3.38/gnome-music-3.38.1.tar.xz : 3bcb1261afa063d3f52b7015b5ed6fad77a54e03d2aae205b68698660749aae9
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : Music is the new GNOME music playing application.
description: |
    Music is the new GNOME music playing application. It aims to combine an elegant and immersive browsing experience with simple and straightforward controls.
builddeps  :
    - pkgconfig(exempi-2.0)
    - pkgconfig(flac)
    - pkgconfig(gee-0.8)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(grilo-0.3)
    - pkgconfig(grilo-plugins-0.3)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(goa-1.0)
    - pkgconfig(icu-i18n)
    - pkgconfig(libcue)
    - pkgconfig(libdazzle-1.0)
    - pkgconfig(libexif)
    - pkgconfig(libgsf-1)
    - pkgconfig(libmediaart-2.0)
    - pkgconfig(libnautilus-extension)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(poppler-glib)
    - pkgconfig(py3cairo)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python3)
    - pkgconfig(taglib)
    - pkgconfig(totem-plparser)
    - pkgconfig(upower-glib)
    - pkgconfig(vorbis)
    - grilo-plugins
    - gvfs-devel
    - itstool
    - python3-dbus
    - python-requests
    - tracker-devel # Change to pkgconfig(tracker-sparql-3.0) after upgrade push
    - vala
rundeps    :
    - dleyna-connector-dbus
    - dleyna-server
    - grilo-plugins
    - libdazzle
    - python3-cairo
    - python3-dbus
    - python-gobject
    - python-requests
    - tracker
setup      : |
    %patch -p1 < $pkgfiles/grltrackerwrapper-Fix-artist-queries.patch
    %patch -p1 < $pkgfiles/grltrackerwrapper-Remove-quotes.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
